FROM openjdk:8-jdk-alpine
MAINTAINER dhanaraj
COPY target/calculator-operation-0.0.1-SNAPSHOT.jar calculator-operation-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/calculator-operation-0.0.1-SNAPSHOT.jar"]